### ISSUE TITLE
Help me please

### ISSUE THREAD

**Issue by jairforero** [ushtipak/songfetch#1]
unexpected directory layout:
        import path: _/C_/Users/JairForero/go/src/github.com/ushtipak/songfetch/xperimental
        root: C:\Users\JairForero\go\src
        dir: C:\Users\JairForero\go\src\github.com\ushtipak\songfetch\xperimental
        expand root: C:\Users\JairForero\go\
        expand dir: C:\Users\JairForero\go\src\github.com\ushtipak\songfetch\xperimental
        separator: \

**Comment by ushtipak** [comment]
It seems like you're trying to run in under Windows and I haven't tested it there :)

If you don't have any Linux distros around you can try to installing one under VirtualBox (I'd suggest Debian)
OR you can try installing Tesseract under Windows (https://github.com/tesseract-ocr/tesseract/wiki#windows)

In either way you'll need some system packages for the OCR so Deb makes again more sense :)

```sudo apt install -y libleptonica-dev tesseract-ocr libtesseract-dev```
```go get -t github.com/otiai10/gosseract```

Hope that helps!
-M :)
